# Configuración del BX Trender Bot
# Archivo de configuración externa para facilitar cambios sin modificar código

# Configuración de la base de datos
database:
  file: "prices.db"
  backfill_years: 4
  update_period: "60d"
  request_delay: 1.0

# Tickers y timeframes a monitorear
trading:
  tickers: ["AAPL", "MSFT", "NVDA"]
  timeframes: ["1d", "1wk", "1mo"]  # daily, weekly, monthly

# Parámetros del indicador BX Trender
indicators:
  # Parámetros short term
  short_l1: 5
  short_l2: 20
  short_l3: 5
  t3_length: 5
  t3_v: 0.7
  
  # Parámetros long term
  long_l1: 20
  long_l2: 5

# Configuración de Telegram
telegram:
  token: ""  # Se debe configurar en .env
  chat_id: ""  # Se debe configurar en .env
  max_retries: 3
  retry_delay_base: 2  # Para exponential backoff
  # Configuración de batching para evitar spam
  batching:
    enabled: true
    max_alerts_per_batch: 5  # Máximo número de alertas por mensaje
    batch_timeout_seconds: 30  # Tiempo máximo para agrupar alertas
    critical_states: ["green_hh", "red_ll"]  # Estados que requieren notificación inmediata
    summary_enabled: true  # Enviar resumen diario
    summary_time: "18:00"  # Hora para enviar resumen diario (formato HH:MM)

# Configuración de logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file_level: "DEBUG"
  console_level: "INFO"
  log_dir: "logs"
  max_log_files: 30  # Número máximo de archivos de log a mantener

# Configuración de monitoreo
monitoring:
  health_check_interval: 300  # segundos
  metrics_enabled: true
  alert_on_errors: true

